### ISSUE TITLE
Unwanted behavior of select2 when switching between view and update mode and back

### ISSUE THREAD

**Issue by bartkanis** [kartik-v/yii2-detail-view#103]
Hi Karik, 
I found some, in my view unwanted behavior when using a select2 widget. It occurs when switching from view to update mode, changing the value of the select2 and go back to view mode without saving. The detail view displays the original value as expected. When switching back to update mode, not this original value is selected in the select2 widget, but the value that was selected the first time in update mode. 
This problem can be reproduced in the detail-view-demo using the author field. When the demo starts the field contains "John Steinbeck". Go to update mode and change the field to "Aldus Huxley". Now go back to view mode, without saving. "John Steinbeck" appears again as expected. Now go back to update mode and "Aldus Huxley" is selected. 
Kind regards,
Bart

**Comment by kartik-v** [comment]
Cannot reproduce your use case nor can I see the behavior on the demo. It works as expected.
