### ISSUE TITLE
Getting unknown property: kartik\detail\DetailView::pluginDestroyJs

### ISSUE THREAD

**Issue by thyseus** [kartik-v/yii2-detail-view#105]
I get this exception:

Getting unknown property: kartik\detail\DetailView::pluginDestroyJs

after doing an composer update to 346c067db89564ca906f28dc757b3133235e0361 .

**Comment by thyseus** [comment]
Update: the problem occurs when switching from = 1.7.0 to >= 1.7.1 .

**Comment by execut** [comment]
I also got the bug, I temporarily added variable in this class until the next update

**Comment by kartik-v** [comment]
The latest stable release is v1.7.4 - not sure why you are using an older version.

**Comment by thyseus** [comment]
The problem appears on all versions newer than 1.7.0 - including 1.7.4.

**Comment by kartik-v** [comment]
There [should be no such error because of this](https://github.com/kartik-v/yii2-detail-view/blob/master/DetailView.php#L477)

**Comment by kartik-v** [comment]
There [should be no such error in v1.7.4 - check why...](https://github.com/kartik-v/yii2-detail-view/blob/master/DetailView.php#L477) as this property already exists. You may need to cross check if you are using the right versions.

**Comment by Ramonvandenheuvel** [comment]
I got this error after installing Yii2-helpers using composer.

Because then composer does this:

>   - Removing kartik-v/yii2-detail-view (v1.7.4)
>   - Installing kartik-v/yii2-detail-view (v1.7.1)

Removing Yii2-helpers using composer does this:

>   - Removing kartik-v/yii2-helpers (dev-master 54262f6)    
>   - Installing kartik-v/yii2-helpers (v1.3.5)
>     Loading from cache
> 
>   - Removing kartik-v/yii2-detail-view (v1.7.1)
>   - Installing kartik-v/yii2-detail-view (v1.7.4)
>     Loading from cache

And then the error is gone.

**Comment by cadr-sa** [comment]
Thanks @Ramonvandenheuvel  for this trick , it fixed my issue

**Comment by thyseus** [comment]
Thanks to @Ramonvandenheuvel - this really does it. A pr dealing with this issue has been proposed.

**Comment by agussuhartono** [comment]
i'm have same error
on my project, **kartik-v/yii2-detail-view ** install automatically after i'm install **warrence/yii2-kartikgii**.

warrence/yii2-kartikgii use "kartik-v/yii2-detail-view.": "*"  instead  "kartik-v/yii2-detail-view": "@dev", 
so it's install  kartik-v/yii2-detail-view v1.7.1 not v1.7.4.

i try add  "kartik-v/yii2-detail-view": "@dev" on root , than composer install last update, and of course, work correctly
