### ISSUE TITLE
multiple detailviews on one page breaks widgets

### ISSUE THREAD

**Issue by akorinek** [kartik-v/yii2-detail-view#111]
I have multiple detail views on one page using this code:
`
$ii = 0;
    //supply details
    foreach ($model->getLinkedSupplies() as $usage)
    {
        $attributes = [];
        $attributes[] = 
        [
            'attribute' => 'supply_id',
            'format' => 'raw',
            'type' => DetailView::INPUT_SELECT2,
            'value' => $usage->supply->name,
            'widgetOptions'=>[
                'data' => ArrayHelper::map(Supply::find()->all(),'id','name'),
                'options' => ['placeholder' => 'Select...'],
                'pluginOptions' => ['allowClear'=>false, 'width'=>'100%'],
            ],
            'valueColOptions'=>['style'=>'width:30%']
        ];        
        $attributes[] = ['attribute' => 'units'];
        if ($user->isStaff() == true) {
            $attributes[] = ['attribute' => 'donotbill', 'type' => DetailView::INPUT_SWITCH];
        }
        $attributes[] = ['attribute' => 'created_at', 'displayOnly' => true];
        $attributes[] = ['attribute' => 'created_by', 'format' => 'raw', 'value' => $usage->createUser->fullNameClickable, 'displayOnly' => true];
        $attributes[] = ['attribute' => 'updated_at', 'displayOnly' => true];
        $attributes[] = ['attribute' => 'updated_by', 'format' => 'raw', 'value' => $usage->updateUser->fullNameClickable, 'displayOnly' => true];
        
        if ($user->isStaff() == true || $usage->createUser->id == $user->id)
        {
            $editable = true;
            $mode = 'edit';
            $buttons2 = '{reset} {save} {delete}';
            $buttons1 = '{update} {delete}';
        }       
        else {
            $editable = false;
            $mode = 'view';
            $buttons2= '';
            $buttons1 = '';
        }
        
         echo DetailView::widget([
            'model' => $usage,
            'condensed' => true,
            'container' => ['id' => 'detailview-supply' . (string) $ii],
            'hover' => true,
            'mode' => $mode,
            'enableEditMode' => $editable,
            'panel' => [
                'heading' => 'Supply: ',
                'type' => DetailView::TYPE_INFO,
            ],
           'buttons1' => $buttons1,
           'buttons2' => $buttons2,
           'attributes' => $attributes,
           'formOptions' => ['action' => Url::to(['view','id' => $usage->id])],
           'alertContainerOptions' => ['class'=>'hide'],
           'deleteOptions'=>[ 
                'url' => Url::to(['delete']),
                'params' => ['id' => $usage->id, 'custom_param' => true,],
            ]
        ]);
       $ii++;
    }
`

The first detailview gets rendered properly, but the next ones have broken widgets (select2, checkbox). Saving and editing works though. I set the container id different for each detail view widget, do I have to do something to each widget as well?

**Comment by kartik-v** [comment]
It naturally will not work because you are trying to use same model and attribute name to generate the fields which will result in duplicate HTML identifiers for the inputs and widgets and they will get broken...

**Comment by shaik305** [comment]
Can you please elaborate on generating unique identifiers in detail view widget @kartik-v

**Comment by shaik305** [comment]
I figured it out myself.. I just need to provide unique container id in detail view
