### ISSUE TITLE
kvInitPlugin is not defined

### ISSUE THREAD

**Issue by jonmer09** [kartik-v/yii2-detail-view#115]
Hi, 

I am getting this error, one function of kvx-widgets.js file is missing.

`kvInitPlugin(jQuery("#w1-container").kvSelector(), function(){ ... }`

i can fix it when i register the widget asset.

`\kartik\widgets\WidgetAsset::register($view)`

**Comment by kartik-v** [comment]
You need to update to the latest release of kartik-v/yii2-krajee-base... check your composer settings.

**Comment by kartik-v** [comment]
Will update on this.
