### ISSUE TITLE
How to Display model attribute in mode horizontal

### ISSUE THREAD

**Issue by siulluz** [kartik-v/yii2-detail-view#123]
Hi Kartik!
how can I use standard DetailView widget in yii2 on horizontal mode ? It is possible change this configuration?
![detailview](https://cloud.githubusercontent.com/assets/18687049/16245934/0108e566-37d1-11e6-8975-a7b37552da5f.png)

Thank you for you attention

**Comment by kartik-v** [comment]
You may try setting the `columns` within the attributes config as described in the demo
