### ISSUE TITLE
Adding a 'create new' button to edit mode

### ISSUE THREAD

**Issue by amlopezalonso** [kartik-v/yii2-detail-view#127]
Hi,

May I suggest adding a 'create new' button to the edit mode? As by gii defaults, a succesful create action redirects to view action, so it would be useful having a 'plus' in the panel. 

Superb work BTW.

Kind regards,
Antonio

**Comment by sercon** [comment]
Just add buttons1... eg

```
    <?= DetailView::widget([
        'buttons1' => Html::button('<i class="glyphicon glyphicon-plus" style="color:white"></i>', ['title' => "New", 'data-toggle' => "tooltip", 'data-container' => "body",'id'=>'add','type'=>'button', 'value' => Url::to(['create']),'title' => $this->title, 'class'=>'showModalButton abutton']) 
        .'{update} {delete}',
```

**Comment by amlopezalonso** [comment]
Nice tip, thanks. Nevertheless I would recommend adding such a button to vanilla DetailView.

Closing anyway.

Antonio

**Comment by kartik-v** [comment]
Yes your own other buttons can be added using the ability to configure additional buttons via `buttons1` and `buttons2` provided in the extension.
