### ISSUE TITLE
widgetOptions not working as expected?

### ISSUE THREAD

**Issue by amlopezalonso** [kartik-v/yii2-detail-view#128]
Hi Kartik:

I use a setting like this in order to  configure 2amigos' TinyMCE widget:

```
 'tinyMceSingleParams' => [
           'options' => ['rows' => 1],
           'language' => 'es',
           'clientOptions' => [
                       'menubar' => false,
                       'forced_root_block' => '',
                       'force_br_newlines' => false,
                       'force_p_newlines' => false,
                       'entity_encoding' => 'raw',
                       'plugins' => ["charmap code"],
                       'toolbar' => "code removeformat | undo redo | italic | charmap",
             ],
     ],
```

So in ActiveForm I can go:

`<?= $form->field($model, 'titulo')->widget(TinyMce::className(), Yii::$app->params['tinyMceSingleParams']) ?>`

However in your DetailView widget I cannot do:

```
 [
    'attribute' => 'titulo',
    'format' => 'raw',
    'type' => 'widget',
     'rowOptions' => ['class' => 'kv-view-hidden'],
     'widgetOptions' => ['class' => TinyMce::classname(), Yii::$app->params['tinyMceSingleParams']],
     'value' => !empty($model->enlaceBibliografia($model)) ? Html::a($model->titulo, $model->enlaceBibliografia($model), ['target' => '_blank']) : $model->titulo,
 ],

```

as I'm getting a _**Setting unknown property: dosamigos\tinymce\TinyMce::0**_

Is this an intended behavior? If so, which could be the best approach to workaround it? 

Kind regards,
Antonio

**Comment by amlopezalonso** [comment]
I finally found a workaround:

    'widgetOptions' => ArrayHelper::merge(['class' => TinyMce::classname()], Yii::$app->params['tinyMceSingleParams']),

**Comment by kartik-v** [comment]
Yes.. its the way you merge the array options (more a PHP coding issue).
