### ISSUE TITLE
Not able to change the message with krajeeDialogSettings

### ISSUE THREAD

**Issue by jeroenk22** [kartik-v/yii2-detail-view#129]
Hi Kartik,

I'm trying to change the delete message in your DetailView widget using `krajeeDialogSettings`.
I'm able to change the `type`, the `title`, the `size` etc. But somehow I'm not able to change the message.

My code:

    'krajeeDialogSettings' => [
        'options' => [
            'title' => 'Verwijderen?',
            'message' => 'Weet u zeker dat u deze opdracht wilt verwijderen?'
        ]
    ],

It still shows the original message: "Are you sure you want to delete this item?"

![screenshot_dialog](https://cloud.githubusercontent.com/assets/3177682/18826508/fbfadd7e-83cd-11e6-8291-26e14d02b08d.png)

Is this a bug?

**Comment by kartik-v** [comment]
No it is not a bug but a wrong configuration from your end.

You need to set the message within `deleteOptions['confirm']` [as mentioned here](https://github.com/kartik-v/yii2-detail-view/blob/master/DetailView.php#L464).

**Comment by jeroenk22** [comment]
Thank you for your quick response! Problem solved ;)
