### ISSUE TITLE
Dropdown forces to use attribute

### ISSUE THREAD

**Issue by amlopezalonso** [kartik-v/yii2-detail-view#130]
Hi Kartik,

In ActiveForm I used the following to display a dropdown that modifies the behavior of a calendar widget:

`Html::dropDownList(null, null, [
              'julian' => Yii::t('app', 'Julian Calendar'),
              'gregorian' => Yii::t('app', 'Gregorian Calendar'),
    ], ['id' => 'selectCalendar', 'class' => 'form-control'])`

You can see there is no attribute involved because I only need the 'id' to make the widget work. However in your enhanced DetailView I'm forced to use an attribute because if not an error is issued even when I specify 'label' and 'value':

`[
    'attribute' => 'calendar',
    'label' => Yii::t('app', 'Calendar Type'),
    'type' => 'dropDownList',
    'value' => 'julian',
    'items' => [ 'julian' => Yii::t('app', 'Julian Calendar'),
                      'gregorian' => Yii::t('app', 'Gregorian Calendar')],
    'options' => ['id' => 'selectCalendar'],
    'rowOptions' =>  ['class' => 'kv-view-hidden'],
],`

Thanks a lot,
Antonio

**Comment by kartik-v** [comment]
Suggest if you can set a non database attribute in your model to achieve your scenario?
