### ISSUE TITLE
{buttons} tag defined in mainTemplate is not working

### ISSUE THREAD

**Issue by annevandervelden** [kartik-v/yii2-detail-view#132]
The {buttons} defined in mainTemplate are rendered, but not clickable.
I suspect this is due to the fact that the button tag is rendered outside the main container.
 
A solution to render the button tag within the current container is replacing line:

DetailView.php line:

    $output = strtr(
            $this->mainTemplate, ['{detail}' => Html::tag('div', $output, $this->container)]
        );
  By:

    $output = strtr(
            Html::tag('div', $this->mainTemplate, $this->container), ['{detail}' => $output]
        );

**Comment by syedmuneer** [comment]
Hello,
Any plans to merge this fix soon?
