### ISSUE TITLE
kv-view-hidden class has no effect when enableEditMode is false

### ISSUE THREAD

**Issue by amlopezalonso** [kartik-v/yii2-detail-view#133]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest `master` branch of yii2-detail-view.
- [X] This is not an usage question. I confirm having gone through and read the [documentation](http://demos.krajee.com/detail-view) and [demos](http://demos.krajee.com/detail-view-demo).
- [X] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [X] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. 'enableEditMode' => false
2. [
               'attribute' => 'myAttribute',
               'rowOptions' => ['class' => 'kv-view-hidden'],
     ],

## Expected behavior and actual behavior

When I follow those steps, I see myAttribute being displayed in view mode.

I was expecting DetailView to not display it. It does behave correctly when 'enableEditMode' => true.

#### Browsers

- [X] Google Chrome
- [X] Mozilla Firefox

#### Operating System

- [X] Linux

#### Libraries

- jQuery version: 2.2.4
- yii2-detail-view version: 1.7.5

## Isolating the problem

- [ ] This bug happens [on the demos page](https://demos.krajee.com/detail-view-demo)
- [X] The bug happens consistently across all tested browsers
- [X] This bug happens when using yii2-detail-view without other plugins.

**Comment by kartik-v** [comment]
You should not be using `kv-view-hidden` for doing this... simply use the bootstrap inbuilt css class `hide` or set `style` to `display:none`.
