### ISSUE TITLE
Select2 in Detailview in Modal - Searchfield Bug

### ISSUE THREAD

**Issue by Shinidoki** [kartik-v/yii2-detail-view#137]
There seems to be a bug with using a select2 widget in the detailview when having the detailview inside of a modal window.

You can see the bug on the modal example here: http://demos.krajee.com/detail-view#usage
Selecting entries works, but using the search doesn't.

Tried with latest commit (af3438e4f929a32029fe03491c980a7b741a2d3b), Firefox 50.0.2 and Chrome 54.0.2840.99.

Using the select2 widget without the detailview works inside the same modal.

**Comment by kartik-v** [comment]
No it is a Bootstrap Modal issue - that you need to configure.

Set `tabindex` to `false` for the Modal Options.

This has been updated in the [demo](http://demos.krajee.com/detail-view#usage) which you can cross check
