### ISSUE TITLE
INPUT_CHECKBOX_BUTTON_GROUP or INPUT_RADIO_BUTTON_GROUP lack implementation

### ISSUE THREAD

**Issue by bobonov** [kartik-v/yii2-detail-view#142]
- yii2-detail-view version: 1.7.6
Implementing a datailview form using INPUT_CHECKBOX_BUTTON_GROUP or INPUT_RADIO_BUTTON_GROUP throw the error
Invalid input type '{$input}' defined for the attribute.....
It seem that the implementation in incomplete.
The two widget need to be inserted in both $_inputsList and $_dropDownInputs array.
The form class to be used must be \kartik\form\ActiveForm (where the two are defined) and not yii\widgets\ActiveForm

**Comment by kartik-v** [comment]
Yes the reason this was not done was it needs dependency on `kartik-v/yii2-widget-activeform`.... if this is desired then the `composer.json` needs to be updated to include the above dependency. For people who want to use it with default `yii\widgets\ActiveForm` these options may not be available.

**Comment by kartik-v** [comment]
Closed via #143
