### ISSUE TITLE
DetailView & AJAX-driven Select2

### ISSUE THREAD

**Issue by amlopezalonso** [kartik-v/yii2-detail-view#144]
Hi Kartik,

I'm combining your DetailView and Select2 widgets and found the following behavior. In view I have:

     [
               'attribute' => 'bibliography_id',
               'format'    => 'raw',
               'type'      => DetailView::INPUT_SELECT2,
               'value'     => function ($form, $widget) { <my_own_stuff_for_VIEW_mode> },
               'widgetOptions' => ['initValueText' => $model->bibliography->title, 'options' => ['placeholder' => Yii::t('app', 'Select...'),
                                    'pluginOptions' => [
                                            'allowClear'         => true,
                                            'minimumInputLength' => 3,
                                            'maximumInputLength' => 20,
                                            'language'           => Yii::$app->language,
                                            'ajax' => [
                                                'url'            => \yii\helpers\Url::to(['search-doc']),
                                                'dataType'       => 'json',
                                                'delay'          => 250,
                                            ],
                                            'errorLoading'       => new JsExpression("function () { return '".Yii::t('app', 'Waiting...')."'; }"),
                                            'escapeMarkup'       => new JsExpression("function (markup) { return markup; }"),
                                            'templateResult'     => new JsExpression("function (bibliography) { return '<b>' + bibliography.text + '</b> <i>(' + bibliography.title + ')</i>'; }"),
                                            'templateSelection'  => new JsExpression("function (bibliography) { return bibliography.text; }"),
                                        ],
                                  ],
                ],
    ], 

However, AJAX seems to not being fired up at all when entering EDIT mode as it does in "create" action. DetailView in EDIT mode shows existing value as per `initValueText`, but trying to modify it opening Select2 box and typing in it just returns empty results (not even displays either placeholder or "searching" warnings).

Is DetailView not straightly compatible with AJAX-driven Select2?

**Comment by kartik-v** [comment]
Not sure on this... have you tried it with default mode set to edit mode (instead of view)?

**Comment by amlopezalonso** [comment]
I had to rewrite ajax piece as follows:

    'ajax' => [
               'url' => \yii\helpers\Url::to(['bibliography/search-doc']),
               'dataType' => 'json',
               'data'  => new JsExpression("function (params) { return {q: params.term, p: params.page}; }"),
               'delay' => 250,
               'cache' => true,
              ],

Thanks lots for your time
