### ISSUE TITLE
hashVarLoadPosition unknown property show after update to 1.8.9

### ISSUE THREAD

**Issue by adiramardiani** [kartik-v/yii2-detail-view#149]

**Comment by BenasPaulikas** [comment]
same issue for me. Sad :(

**Comment by kartik-v** [comment]
Note that the version `v1.8.9` you mention is the latest release of `yii2-krajee-base` which you seem to have installed.

You also need to ensure you have the latest / updated release of this extension `yii2-detail-view` - the latest release currently being `v1.7.6`.
