### ISSUE TITLE
Release 1.7.6 keeps being reused

### ISSUE THREAD

**Issue by drsdre** [kartik-v/yii2-detail-view#151]
Why is release version 1.7.6 being re-released? 
It was original released on december 14th 2016 and it got changed to release on May 4th with commit https://github.com/kartik-v/yii2-detail-view/commit/1bd219ec301d10fd56162a98619c36769400718b#diff-cbb171ef84905c970b43d134d9aebdd1.

Seven days ago version 1.7.6 got re-re-released again according to https://github.com/kartik-v/yii2-detail-view/releases.

It's making it very hard to troubleshoot version compatibility issues.

**Comment by kartik-v** [comment]
It was a release under development and not tagged. The dates were continually changed in the change log until the Version 1.7.6 was finally tagged in the repo releases.

**Comment by drsdre** [comment]
Thank you for the clarification.
