### ISSUE TITLE
value Closure first param should be $model, but it's null

### ISSUE THREAD

**Issue by tsdogs** [kartik-v/yii2-detail-view#153]
if I configure an attribute like
```
[
    'attribute'=>'name',
    'value'=>function ($model,$widget) {
        return $model['value'];
    }
],
```
this does not work as $model is NULL (I think because it's passing the `$this->_form` as parameter?)

in the yii2 DetailView the first attribute is the model and works as expected.

To solve this we need to use the` $widget->model['value']` insthead.

IMHO the default behaviour should be respected, or documentation should report that the behaviour is not compatible with yii2 DetailView anymore.

**Comment by BenasPaulikas** [comment]
Same for me after doing composer update today

'value' => function($model) was working.

@kartik-v any ideas ?

**Comment by tsdogs** [comment]
Ihmo this should be fixed.
