### ISSUE TITLE
How can i use array as attributes? o use 2 models in the editview 

### ISSUE THREAD

**Issue by racielbd** [kartik-v/yii2-detail-view#154]
Hi Kartik,

I have 2 tables in my db, and what i need is to make only 1 form with all the columns in it.
I tried a few ways one of them like the one that is on this link [https://mrphp.com.au/blog/advanced-multi-model-forms-yii2/](https://mrphp.com.au/blog/advanced-multi-model-forms-yii2/)
but in the model i have a array 

So after i create the "Form Model". How can i do this in the detail-view way on the edit mode.
```
<div class="product-form">
    <?php $form = ActiveForm::begin(); ?>
    <?= $productForm->errorSummary($form); ?>
    <fieldset>
        <legend>Product</legend>
        <?= $form->field($productForm->product, 'name')->textInput() ?>
    </fieldset>
    <fieldset>
        <legend>Parcel</legend>
        <?= $form->field($productForm->parcel, 'code')->textInput() ?>
        <?= $form->field($productForm->parcel, 'width')->textInput() ?>
        <?= $form->field($productForm->parcel, 'height')->textInput() ?>
        <?= $form->field($productForm->parcel, 'depth')->textInput() ?>
    </fieldset>
    <?= Html::submitButton('Save'); ?>
    <?php ActiveForm::end(); ?>
</div>
```
Note that the attribute is like ($productForm->product, 'name') but in detail-view i only can use a string and if a use 
`attribute=>´name´`
it dosen´t work
Thanks

**Comment by kartik-v** [comment]
DetailView by nature only supports one model... You may have to use other non db fields in the model to send bv data to your related model.

**Comment by racielbd** [comment]
That´s what i´m trying to aboit..., it works, but make my model a little ugly...  its ok..., i will adapt.. the model that way...
thanks for the quick response....
great work
