### ISSUE TITLE
Rendered scrollbar when it's not needed in Chrome with zoom options 100%

### ISSUE THREAD

**Issue by MattiCerio** [kartik-v/yii2-detail-view#156]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest `master` branch of yii2-detail-view.
- [X] This is not an usage question. I confirm having gone through and read the [documentation](http://demos.krajee.com/detail-view) and [demos](http://demos.krajee.com/detail-view-demo).
- [ ] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [X] I have attempted to find the simplest possible steps to reproduce the issue.
- [X] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. Open Chrome (my version 63.0.3239.132)
2. Go to http://demos.krajee.com/detail-view-demo
3. Change zoom page to 100% 

## Expected behavior and actual behavior

When you set zoom to 100% appears the scrollbar, but in 90% and 110% disappears

#### Browsers

- [X] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

#### Operating System

- [X] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

#### Libraries

- jQuery version: Version of demo
- yii2-detail-view version: Version of demo

## Isolating the problem

- [X] This bug happens [on the demos page](https://demos.krajee.com/detail-view-demo)
- [ ] The bug happens consistently across all tested browsers
- [X] This bug happens when using yii2-detail-view without other plugins.

**Comment by kartik-v** [comment]
This depends on the settings of your display. By default the `responsive` property is set to `true` to allow the bootstrap responsive table styling to be enabled and scrollbar will be shown based on display width and content width. If you do not want a scrollbar - set the `responsive` property to `false`.
