### ISSUE TITLE
DetailView with EnableEditMode true inside ActiveForm

### ISSUE THREAD

**Issue by MoonLoq** [kartik-v/yii2-detail-view#157]
When use DetailView with EnableEditMode=true inside ActiveForm
```
use kartik\form\ActiveForm;
$form = ActiveForm::begin();
echo kartik\detail\DetailView::widget([
    'model' => $model,
blablabla
]);
echo Html::submitButton('Accept price', ['name' => 'submitButton', 'value' => 'acceptPrice', 'class' => 'btn btn-info']);
$form->end();

```
in generated Html tag `<form>` closes after DetailView.
Button 'Accept Price' is not included in `<form> </form>`.
With EnableEditMode=false all right.

**Comment by kartik-v** [comment]
It is obvious that you cannot do what you are doing because it will break the HTML markup because you are NESTING one `form` within another.

The `kartik\detail\DetailView` widget renders its own `ActiveForm` with `enableEditMode` set to `true`. You cannot embed it within another form.
