### ISSUE TITLE
Design is crashed with footer enabled

### ISSUE THREAD

**Issue by sptik12** [kartik-v/yii2-detail-view#168]
Hi Kartik!

Thanks for your components!

After 'composer update we found that footer design is crashed with the following options enabled:
'footer' => true,
'footerOptions' => ['template' => '{buttons}']

Please take look at screenshot:
https://prnt.sc/l7vxx4

We use Bootstrap 3.

**Comment by kartik-v** [comment]
There are some changes and you cannot set the footer that way:

You need to set the panel footer as below:

```php
echo DetailView::widget([
    'panel' => [
        'footer' => 'This must be some markup which you want to display in the footer', // you can set it to `false` to hide footer
        'footerOptions' => ['class' => 'some_css_class']  // this is HTML attributes only
    ],
    // other settings
]);
```
