### ISSUE TITLE
Hide empty elements

### ISSUE THREAD

**Issue by a-komarev** [kartik-v/yii2-detail-view#17]
Is there any way to hide attribute rows with empty values and values == 0 from VIEW mode but display them in EDIT mode?

**Comment by ramadan35** [comment]
Its good to have this as a feature

**Comment by kartik-v** [comment]
Resolved via upgrade to release v1.7.0 This release includes various new enhancements and BC breaking changes.

Check the new `hideIfEmpty` property for the use case as required in this issue.

**Comment by a-komarev** [comment]
That's great. Thank you very much.

**Comment by cornernote** [comment]
This causes issues in striped tables.

![image](https://cloud.githubusercontent.com/assets/51875/9213906/d7a0db94-40d6-11e5-98aa-1510c2bac25a.png)
