### ISSUE TITLE
Override Default Confirm Box for Delete Button

### ISSUE THREAD

**Issue by buttflattery** [kartik-v/yii2-detail-view#170]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of yii2-detail-view.
- [x] This is not an usage question. I confirm having gone through and read the [documentation](http://demos.krajee.com/detail-view) and [demos](http://demos.krajee.com/detail-view-demo).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. Install the extension
2. Initialize the `DetailView` with the following code where specifying `krajeeDialogSettings` with `['overrideYiiConfirm' => false, 'useNative' => true]`

```
use kartik\detail\DetailView;

echo DetailView::widget(
    [
        'model' => $model,
        'condensed' => true,
        'hover' => true,
        'mode' => DetailView::MODE_VIEW,
        'panel' => [
            'heading' => 'User # ' . $model->id,
            'type' => DetailView::TYPE_INFO,
        ],
        'buttons1' => '{view} {delete}',
        'deleteOptions' => [
            'label' => 'Delete Now',
        ],
        'krajeeDialogSettings' => ['overrideYiiConfirm' => false, 'useNative' => true],
        'attributes' => [
            'id',
            'username',
            ['attribute' => 'created_at', 'type' => DetailView::INPUT_DATE],
        ],
    ]

);

```

3. Now if i want to override the default confirm box which is basically a native javascript confirm in Yii2 and use `sweetalert` to display the confirm box i would normally do the following for any `a` which uses `data-confirm` attribute

```
yii.confirm = function (message, okCallback, cancelCallback) {
    swal({
            text: message,
            icon: 'warning',
            buttons : {
                cancel : {
                    text : "Oops! No",
                    value : null,
                    visible : true,
                    className : "",
                    closeModal : true
                },
                confirm : {
                    text : "Delete It Already",
                    value : true,
                    visible : true,
                    className : "",
                    closeModal : true
                }
            },
            closeOnClickOutside: true
    }).then((selection) => {
     if(selection){okCallback.call();}else{cancelCallback.call();}
    });
}
```

## Expected behavior and actual behavior
This normally works but when working with the `kartik\DetailView` this never get called even if i use the `'overrideYiiConfirm' => false, 'useNative' => true` it always keeps on showing the default native confirm box.

I have looked into this issue too https://github.com/kartik-v/yii2-grid/issues/757 , where you have asked to use the above listed settings in case one needs to override the default doalog or use custom.

Isnt there an option to provide a callback function to render the custom view to which i can assign an id and bind the confirm box?

## Environment
Ubuntu 14.04
Php 7.2
Bootstrap 3

#### Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [x] Internet Explorer
- [ ] Safari

#### Operating System

- [ ] Windows
- [ ] Mac OS X
- [x] Linux
- [ ] Mobile

#### Libraries

- jQuery version: 3.3.1
- yii2-detail-view version: `dev-master`

## Isolating the problem

- [ ] This bug happens [on the demos page](https://demos.krajee.com/detail-view-demo)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using yii2-detail-view without other plugins.

**Comment by buttflattery** [comment]
Strangely, what I have to work out was to rule out the 

`'overrideYiiConfirm' => false, 'useNative' => true`

and override the `krajeeDialog.confirm` instead of overriding the `yii.confirm` like below

```
krajeeDialog.confirm = function (message, callback) {
swal({
            text: message,
            icon: 'warning',
            buttons : {
                cancel : {
                    text : "Oops! No",
                    value : null,
                    visible : true,
                    className : "",
                    closeModal : true
                },
                confirm : {
                    text : "Delete It Already",
                    value : true,
                    visible : true,
                    className : "",
                    closeModal : true
                }
            },
            closeOnClickOutside: true
    }).then((selection) => {
     if(selection){okCallback.call();}}
    });
}
```


Can you please add come info as if why the provided option does not allow me to override the `yii.confirm` as all the extensions like `Detail` ,`Grid` and `TreeView` use the `yii2-dialog` extension for prompts and alerts and almost all have these `krajeeDialogSettings` option.

**Comment by buttflattery** [comment]
up

**Comment by kartik-v** [comment]
It seems you are using multiple usages of krajee dialogs in the same page (e.g. via DetailView, via GridView etc.)

If you need different configurations for multiple dialogs in the same page then - also set the `krajeeDialogSettings[libName]` property to something unique and different for each instance.
