### ISSUE TITLE
How to remove hints from fieldConfig template for all fields?

### ISSUE THREAD

**Issue by thadudexx** [kartik-v/yii2-detail-view#171]
`'formOptions' => [
        'fieldConfig' => [
            'template' => "{input}\n{error}",
         ],
   ],`
doesn´t work for me.

You are setting
`$this->formOptions['fieldConfig']['template'] = "{input}\n{hint}\n{error}";`
in the init method, why not use that as the default value instead of the hardcoded string?

thank you for the great work.

**Comment by kartik-v** [comment]
Set showHints to false within formConfig within formOptions

**Comment by thadudexx** [comment]
Thank you, didn´t see the showHints option.
