### ISSUE TITLE
Grouping attributes

### ISSUE THREAD

**Issue by a-komarev** [kartik-v/yii2-detail-view#18]
I suppose it's enancement too. I need to group attributes.

For example:
```
<tr>
    <th colspan="2" class="detail-group">Group #1</th>
</tr>
<tr>
    <th>First attribute label</th>
    <td><div class="kv-attribute">First attribute value</div></td>
</tr>
<tr>
    <th>Second attribute label</th>
    <td><div class="kv-attribute">Second attribute value</div></td>
</tr>
<tr>
    <th colspan="2" class="detail-group">Group #2</th>
</tr>
<tr>
    <th>Third attribute label</th>
    <td><div class="kv-attribute">Third attribute value</div></td>
</tr>
```

So, this is not really grouping. It's 100% width of label column using colspan. Now you can't create any rows not assigned to a real attribute and you can't change colspan of label column.

Is it possible to implement such feature by extending `\yii\widgets\DetailView` and not rewriting it?

**Comment by kartik-v** [comment]
Resolved via upgrade to release v1.7.0 This release includes various new enhancements and BC breaking changes.

Check the new `group` property at the widget `attributes` level for the use case as required in this issue.

**Comment by a-komarev** [comment]
Thanks a lot!

**Comment by a-komarev** [comment]
Working great. Just one notice. If you have hidden empty rows there is no way to hide groups automatically if only next group available after it.

**Comment by kartik-v** [comment]
Will need javascript... will check later.
