### ISSUE TITLE
BS3: Some fields are misaligned in edit mode

### ISSUE THREAD

**Issue by thadudexx** [kartik-v/yii2-detail-view#186]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of yii2-detail-view.
- [x] This is not an usage question. I confirm having gone through and read the [documentation](http://demos.krajee.com/detail-view) and [demos](http://demos.krajee.com/detail-view-demo).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. Open Demo
2. Switch to Edit mode
3. ![DemoFields](https://user-images.githubusercontent.com/5389906/145383413-e3f2c667-8889-4427-94f7-c1ccd1ee69d5.png)

## Expected behavior and actual behavior

When I follow those steps, I see not centered Book Name, Color, Buy Amount ($), ...

I was expecting all fields to be centered

#### Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

#### Operating System

- [x] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

#### Libraries

- jQuery version:
- yii2-detail-view version:

## Isolating the problem

- [x] This bug happens [on the demos page](https://demos.krajee.com/detail-view-demo)
- [x] The bug happens consistently across all tested browsers
- [ ] This bug happens when using yii2-detail-view without other plugins.

**Comment by kartik-v** [comment]
Resolved via above commit

**Comment by kartik-v** [comment]
Resolved via above commit.

**Comment by thadudexx** [comment]
Thank you very much.
