### ISSUE TITLE
Error: Calling unknown method: kartik\detail\DetailView::initBsVersion()

### ISSUE THREAD

**Issue by strtob** [kartik-v/yii2-detail-view#187]
## Prerequisites

- [ x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ]x The issue still exists against the latest `master` branch of yii2-detail-view.
- [ ]x This is not an usage question. I confirm having gone through and read the [documentation](http://demos.krajee.com/detail-view) and [demos](http://demos.krajee.com/detail-view-demo).
- [ x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [ x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. Install current dev-master version
2. use detailview

## Expected behavior and actual behavior

When I follow those steps, I see...

I was expecting...

#### Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

#### Operating System

- [ ] Windows
- [ ] Mac OS X
- [ x] Linux
- [ ] Mobile

#### Libraries

- jQuery version:
- yii2-detail-view version: dev-master

## Isolating the problem

- [ ] This bug happens [on the demos page](https://demos.krajee.com/detail-view-demo)
- [ x] The bug happens consistently across all tested browsers
- [ ] This bug happens when using yii2-detail-view without other plugins.

I get the following error:

```
<pre>Exception 'yii\base\UnknownMethodException' with message 'Calling unknown method: kartik\detail\DetailView::initBsVersion()' 

in /opt/work/assetor/vendor/yiisoft/yii2/base/Component.php:300

Stack trace:
#0 /opt/work/assetor/vendor/kartik-v/yii2-detail-view/src/DetailView.php(816): yii\base\Component-&gt;__call()
#1 /opt/work/assetor/vendor/kartik-v/yii2-detail-view/src/DetailView.php(794): kartik\detail\DetailView-&gt;initWidget()
#2 /opt/work/assetor/vendor/yiisoft/yii2/base/BaseObject.php(109): kartik\detail\DetailView-&gt;init()
#3 [internal function]: yii\base\BaseObject-&gt;__construct()
#4 /opt/work/assetor/vendor/yiisoft/yii2/di/Container.php(419): ReflectionClass-&gt;newInstanceArgs()
```
I've taken a look into https://github.com/kartik-v/yii2-detail-view/blob/cdeb72a7b04d1e2cc7d7c67ebcba2ee27dd0fb17/src/DetailView.php#L812

```
protected function initWidget()
    {
        $this->_msgCat = 'kvdetail';
        $this->pluginName = 'kvDetailView';
        $this->initBsVersion();
        $notBs3 = !$this->isBs(3);
        if ($notBs3) {
            Html::addCssClass($this->container, 'kv-container-bs4');
        }
```
and as far is I've understood, this must be definded in the interface

https://github.com/kartik-v/yii2-krajee-base/blob/master/src/BootstrapInterface.php

but it doesnt' :-/

**Comment by kartik-v** [comment]
You need to update your packages via composer with all dependencies. You do not seem to have the latest release of dependencies like `yii2-krajee-base` which includes the various traits containing these methods.

**Comment by strtob** [comment]
Thanks a lot kartik! 

I've tried to reinstall, incl. deps, also have installed manually via composer require "kartik-v/yii2-krajee-base": "dev-master" - without success :-/

**Comment by strtob** [comment]
...I've insert it here:

```
class DetailView extends YiiDetailView implements BootstrapInterface
{
    use WidgetTrait;
    use TranslationTrait;

    /**
     * @var string view mode for the detail view
     */
    const MODE_VIEW = 'view';
```

after translationTrait (use kartik\base\BootstrapTrait) which fix the problem...

**Comment by chmoth-yii** [comment]
I am also encountering same issue. tried adding "BootstrapTrait" like @strtob suggested and the error is gone. attaching reference code.

`class DetailView extends YiiDetailView implements BootstrapInterface
{
    use WidgetTrait;
    use TranslationTrait;
    use BootstrapTrait; **<---Manually added. this is Missing in latest version dev-master (1.8.5) thus causing the error**
`
 @kartik-v  But will you be making an official fix for this soon? or are we doing something wrong?

By the way, Hats Off to you for all the effort in making all these wonderful widgets and plugins! Much Appreciated! Cant Thank you Enough.

**Comment by kartik-v** [comment]
Thanks this will be updated.

**Comment by chmoth-yii** [comment]
Thankyou very much for this Quick Reponse!
