### ISSUE TITLE
The DetailView should accept array attributes

### ISSUE THREAD

**Issue by drenty** [kartik-v/yii2-detail-view#22]
The original DetailView does it.

For instance, if you have a hasMany() relationship in your model and you want the model array to be represented as a string via your formatter, you should be able to pass it as an attribute.

Currently it raises an "Array to string conversion" exception.

Great widget though!

**Comment by sucoec** [comment]
Hi kartik, you have amazing components for yii2 that helped me a lot, i have a question, hope that you can help me; i'm passing like you saying but when i go to the detailview it shows me the relational name of the value instead of the value; here's my code:
`<?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'CA_PAR_ID',
            [
             'attribute'=>'CA_CUR_ID',
             'label'=>'Taller/Curso/Capacitación',
             'value'=>'cACUR.CA_CUR_NOM' ->this is the attribute that i'm trying to retrieve
            ],
            'CA_PAR_NOM_EMP',
            'CA_PAR_DIR_EMP',
            'CA_PAR_ENT_PUBLICA',
            'CA_PAR_CALIFICADO',
            'CA_PAR_NUM_EMPLEADOS',
            'CA_PAR_NOM_APE_PAR',
            'CA_PAR_DOC_IDENTIDAD',
            'CA_PAR_EMAIL:email',
            'CA_PAR_CARGO',
            'CA_PAR_TEL_CONVENCIONAL',
            'CA_PAR_NIV_INSTRUCCION',
            'CA_PAR_PROFESION',
            'CA_PAR_FCH_INSCRIPCION',
            'CA_PAR_TEL_CELULAR',
            'CA_PAR_EMP_CONTACTO',
            'CA_PAR_EMP_TELF',
            'CA_PAR_EMP_EXT',
        ],
        'mode' => 'view',
        'bordered' => false,
        'striped' => false,
        'condensed' => true,
        'responsive' => true,
        'hover' => false,
        'hAlign'=>true,
        'vAlign'=>true,
        'fadeDelay'=>true,
    ]) ?>`

Thanks in advance.

**Comment by embula** [comment]
Hi Kartik,

I had this same issue especially wen displaying two columns in one row.
If i place the code this way it doesnt work and keeps giving me the exception : _**The attribute configuration requires the "attribute" element to determine the value and display label**_
`[
               'columns' =>[
                        [
                            'attribute' => 'LoanStatus',
                            'value' => $model->status->LoanStatusName,
                            'valueColOptions' => ['style' => 'width: 30%'],
                        ],
                        
                ],
            ],`
But when I place the code is an single array it works, like below. 
`[
                            'attribute' => 'LoanStatus',
                            'value' => $model->lnStatus->LoanStatusName,
                            'valueColOptions' => ['style' => 'width: 30%'],
                    ],`

How can i achieve this in a nested array ?
