### ISSUE TITLE
Attributes with visible = false not send

### ISSUE THREAD

**Issue by DevilsJin** [kartik-v/yii2-detail-view#30]
Don't know if this is an expected behaviour but if I set **visible** to **false** on a GridView this attribute won't be send when updating.

My DetailView config:
```php
<?= DetailView::widget([
    'model'=>$oUser,
    'condensed'=>true,
    'hover'=>true,
    'mode'=>DetailView::MODE_VIEW,
    'formOptions' => [
        'action' => Url::toRoute( [Yii::$app->controller->id .'/update'] ),
    ],
    'panel'=>[
        'heading'=> "<strong>Benutzer:</strong> ".$oUser->username,
        'type'=>DetailView::TYPE_INFO,
    ],
    'attributes'=>[
        [
            'attribute' => 'id',
            'label' => "Benutzer ID",
            'visible' => FALSE
        ],
        [
            'attribute' => 'username',
            'label' => 'Benutzername',
            'displayOnly' => true
        ],
        [
            'attribute' => 'prename',
            'label' => 'Vorname',
        ],
        [
            'attribute' => 'name',
            'label' => 'Nachname',
        ]
    ]
]); ?>
```
In this case, when I click on edit and save in the DetailView the **id** is not send through post (**name** and **prename** are !).
Also the **username** is not send though I think that is desired because of **displayOnly** set to **true**

**Comment by CristianTan** [comment]
I think you should make the either hidden, or readonly

**Comment by kartik-v** [comment]
As mentioned by @CristianTan - use the new `hidden` property of the kartik\grid\DataColumn.

The `visible` property from yii\grid\DataColumn does not render the column at all.

**Comment by kartik-v** [comment]
The above was assuming its a GridView (since your query mentioned GridView)

if you are using DetailView... then just use a hiddenInput to append to your core detail view using INPUT_RAW ... refer #9 for details on this.

**Comment by kartik-v** [comment]
The above response was assuming its a GridView (since your query mentioned GridView)

if you are using DetailView... then just use a hiddenInput to append to your core detail view column using format as **raw** ... refer #9 for details on this.

**Comment by DevilsJin** [comment]
I've done this DetailView with trying to hide first column.
```php
<?= DetailView::widget([
    'model'=>$oUser,
    'condensed'=>true,
    'hover'=>true,
    'mode'=>DetailView::MODE_VIEW,
    'formOptions' => [
        'action' => Url::toRoute( [Yii::$app->controller->id .'/update'] ),
    ],
    'panel'=>[
        'heading'=> "<strong>Benutzer:</strong> ".$oUser->username,
        'type'=>DetailView::TYPE_INFO,
    ],
    'attributes'=>[
        [
            'attribute' => 'id',
            //'label' => "Benutzer ID",
            'format' => 'raw',
            'value' => Html::activeHiddenInput( $oUser, 'id' )
        ],
        [
            'attribute' => 'username',
            'label' => 'Benutzername',
            'displayOnly' => true
        ],
        [
            'attribute' => 'prename',
            'label' => 'Vorname',
        ],
        [
            'attribute' => 'name',
            'label' => 'Nachname',
        ]
    ]
]); ?>
```
But it doesn't seem to work properly, the 'id' column is rendered, only the cell containing the value is empty in view mode. What's wrong with this ?

**Comment by kartik-v** [comment]
Do not create a new attribute column for you hidden input (SINCE YOU ARE NOT DISPLAYING IT)... just append the hidden input with one of your other columns which you are displaying using RAW format...

```php
     'attributes'=>[
        [
            'attribute' => 'name', // an attribute which is displayed
            //'label' => "Benutzer ID",
            'format' => 'raw',
            'value' => $oUser->name . Html::activeHiddenInput( $oUser, 'id' )
        ], ...
    ]
