### ISSUE TITLE
DetailView current mode

### ISSUE THREAD

**Issue by kroshanin** [kartik-v/yii2-detail-view#31]
When I change mode through buttons or through Object.kvDetailView('setMode',NewMode) - [mode] attributes in objects is not changed.
Code example:

alert($('#myDetailViewId').data('kvDetailView').mode);
$('#myDetailViewId').kvDetailView('setMode','edit');
alert($('#myDetailViewId').data('kvDetailView').mode);

**Comment by kartik-v** [comment]
Note the following:

1.  The `mode` property for the plugin is used for only settng the initial mode when the widget is loaded (this property does not change subsequently)
2. The ID `myDetailViewId` you have in your example must be the `container['id']` property in DetailView widget and not the `options['id']`
