### ISSUE TITLE
Broken 'heading' if only 'footer' is defined

### ISSUE THREAD

**Issue by Commifreak** [kartik-v/yii2-detail-view#39]
I have a problem with the following code:

```
echo DetailView::widget([
	'model' => $model,
	'attributes' => $detailview,
	'panel' => [
//		'heading' => false,
		'footer' => 'Footer'
	]
//	'mode' => DetailView::MODE_EDIT
]);
```

This looks like:

![switch](https://cloud.githubusercontent.com/assets/87267/6285871/5c874360-b901-11e4-8657-e7deccc61b10.PNG)

(Yii 2.0.2, detailview 7cefdf1123)

If I do not define 'panel' (or just heading) all is fine. As soon as I want only footer to appear, the heading shows up automatically.

The detailview is inside a modal, loaded via AJAX.

Bug or feature? Did I missed something?

Thanks in davance :)

**Comment by kartik-v** [comment]
That's because the buttons are displayed in the right corner always. I will try to include an enhancement to make it configurable.

**Comment by kartik-v** [comment]
Will be addressed with other new options via new enhancement #40.

**Comment by Commifreak** [comment]
Awesome, thanks! :)
