### ISSUE TITLE
[1.7.0] 'Array to string conversion' with INPUT_CHECKBOX_LIST if attribute contains array

### ISSUE THREAD

**Issue by Commifreak** [kartik-v/yii2-detail-view#44]
Hi,

I try to use an Checkboxlist with DetailView. Correct me if I'm wrong, but to pre-select already assigned ones, I have to provide an array as attribute type, right?

The following code:

```
$model->roles = ['apache' => 'Apache'];
	[
		'attribute' => 'roles',
		'label' => 'Bla',
		'format' => 'raw',
		'type' => DetailView::INPUT_CHECKBOX_LIST,
		'items' => ['apache' => 'Apache', 'fpm' => 'PHP5-FPM', 'haproxy' => 'HAProxy']
	],
```

prduces:

```
PHP Notice 'yii\base\ErrorException' with message 'Array to string conversion' 

in /var/www/_web/vendor/yiisoft/yii2/helpers/BaseHtml.php:142

Stack trace:
#0 /var/www/_web/vendor/yiisoft/yii2/helpers/BaseHtml.php(142): yii\base\ErrorHandler->handleError(8, 'Array to string...', '/var/www/vhosts...', 142, Array)
#1 /var/www/_web/vendor/kartik-v/yii2-detail-view/DetailView.php(606): yii\helpers\BaseHtml::tag('div', Array, Array)
#2 /var/www/_web/vendor/kartik-v/yii2-detail-view/DetailView.php(567): kartik\detail\DetailView->renderAttribute(Array, 5)
#3 /var/www/_web/vendor/kartik-v/yii2-detail-view/DetailView.php(541): kartik\detail\DetailView->renderDetailView()
#4 /var/www/_web/vendor/yiisoft/yii2/base/Widget.php(73): kartik\detail\DetailView->run()
#5 /var/www/_web/views/server/ajx/details.php(103): yii\base\Widget::end()
#6 /var/www/_web/vendor/yiisoft/yii2/base/View.php(325): require('/var/www/vhosts...')
#7 /var/www/_web/vendor/yiisoft/yii2/base/View.php(247): yii\base\View->renderPhpFile('/var/www/vhosts...', Array)
#8 /var/www/_web/vendor/yiisoft/yii2/web/View.php(210): yii\base\View->renderFile('/var/www/vhosts...', Array, Object(app\controllers\ServerController))
#9 /var/www/_web/vendor/yiisoft/yii2/web/Controller.php(47): yii\web\View->renderAjax('ajx/details', Array, Object(app\controllers\ServerController))
#10 /var/www/_web/controllers/ServerController.php(152): yii\web\Controller->renderAjax('ajx/details', Array)
#11 [internal function]: app\controllers\ServerController->actionEditServerDetails()
#12 /var/www/_web/vendor/yiisoft/yii2/base/InlineAction.php(55): call_user_func_array(Array, Array)
#13 /var/www/_web/vendor/yiisoft/yii2/base/Controller.php(151): yii\base\InlineAction->runWithParams(Array)
#14 /var/www/_web/vendor/yiisoft/yii2/base/Module.php(455): yii\base\Controller->runAction('edit-server-det...', Array)
#15 /var/www/_web/vendor/yiisoft/yii2/web/Application.php(83): yii\base\Module->runAction('server/edit-ser...', Array)
#16 /var/www/_web/vendor/yiisoft/yii2/base/Application.php(375): yii\web\Application->handleRequest(Object(yii\web\Request))
#17 /var/www/_web/web/index.php(12): yii\base\Application->run()
#18 {main}
```

Did I missed something?

Currently working with 1.7.0 stable and Yii 2.0.3.

**Comment by kartik-v** [comment]
You forgot that there is a VIEW mode for the DetailView as well. The EDIT mode dropdown list will accept an array for the value --- but there is no way the Array could be displayed in VIEW mode... you need to change your design to return a string value for VIEW mode.

**Comment by Commifreak** [comment]
Nope, Iam already in edit mode ;)

And why Dropdown? I mean the CheckBoxList.

I'll try to post a complete example on monday.

**Comment by kartik-v** [comment]
Irrespective of whichever mode you are in the widget parses output for both VIEW and EDIT modes together and displays at runtime - whatever mode you toggle. With regards checkboxlist or multiple dropdownlist... it doesn't matter as the configuration is similar ... the array of values will not be parsed for the model attribute in VIEW mode. 

To understand what I am saying... just for a moment forget about this widget... try setting `$model->roles` to an array output and try to display it in default `yii\widgets\DetailView` - you will get the same error... because an array cannot be displayed/echoed like a string.

**Comment by Commifreak** [comment]
Yes, I know that an array cannot be displayed like a string. But how to show the selected items?

```
DetailView::begin([
	'formOptions' => [
		'action' => Yii::$app->urlManager->createUrl(['server/update-server-details'])
	],
	'model' => $model,
	'attributes' => $detailview,
	'buttons1' => '{delete}',
	'buttons2' => '{reset} {save}',
	'panel' => [
		'heading' => false,
		'footer' => '&nbsp;{buttons}',
	],
	'mode' => DetailView::MODE_EDIT
]);
```

attribute:

```
	[
		'attribute' => 'roles',
		'format' => 'raw',
		'type' => DetailView::INPUT_CHECKBOX_LIST,
		'items' => ['apache' => 'Apache', 'fpm' => 'PHP5-FPM', 'haproxy' => 'HAProxy']
	],
```

This alone is working and shows the checkboxes as expected. But how to assign the selected items to it?

```
$model->roles = ['fpm', 'apache']
```
and then open DetailView directly in EditMode returns the posted error.

IF I try this with traditional checkBoxList:

```
$form = bootstrap\ActiveForm::begin();
$model->roles = ['apache'];
echo $form->field($model, 'roles')->checkboxlist(['apache' => 'Apache', 'fpm' => 'FPM', 'bla' => 'blubb']);

bootstrap\ActiveForm::end();
```

Everything is working as expected.

Can you post an example?

**Comment by kartik-v** [comment]
Just set the `value` property within the attribute setting to a comma delimited string instead of an array to display correctly in VIEW mode.

**Comment by manisha27mohit** [comment]
make id as a primary keu works for me

**Comment by mbraidy** [comment]
How to make it work in both modes?

**Comment by racielbd** [comment]
> Just set the value property within the attribute setting to a comma delimited string instead of an array to display correctly in VIEW mode.

This do not work when more than one is selected
`
$i = 0;
foreach (MODEL::find()->all() as $sel):
 $model->field .= $i == 0 ? $sel->field : ', '.$sel->field;
$i++;
endforeach;
`
