### ISSUE TITLE
I want to use select2 in detail-view，But I do't know how to do.

### ISSUE THREAD

**Issue by str2code** [kartik-v/yii2-detail-view#45]
``` php
DetailView::widget([
    'model' => $model,
    'condensed' => false,
    'hover' => true,
    'mode' => Yii::$app->request->get('edit') == 't' ? DetailView::MODE_EDIT : DetailView::MODE_VIEW,
    'panel' => [
        'heading' => $this->title,
        'type' => DetailView::TYPE_INFO,
    ],
    'attributes' => [
    [
        'attribute' => 'type',
        'type' => DetailView::INPUT_SELECT2,
        'data'=>['1'=>'php','2'=>'c#','3'=>'python'],
        'pluginOptions'=>[
            //some code...
        ]
    ],
    'enableEditMode' => true,
```

**Comment by kartik-v** [comment]
Would recommend to read the [docs and demos](http://demos.krajee.com/detail-view).
An example of [Select2 usage with detail view also exists on the demo page](http://demos.krajee.com/detail-view-demo).Click Attributes setup button on demo page to view the attribute configuration.

Use this project page for only logging issues. Try to post generic help related queries on the extension or demo page to get better response.
