### ISSUE TITLE
Form prevent from Delete action

### ISSUE THREAD

**Issue by lhviet** [kartik-v/yii2-detail-view#46]
Hi,
Firstly, thank you very much for your great widget.

The issue is when I implement the delete button as below:
```php
'buttons1'=>'{delete}',
        'deleteOptions'=>[
            'url'=>['/slider/delete', 'position' => $model->position, 'language_id' => $model->language_id],
            'data'=>[
                'confirm'=>Yii::t('app',
                    'Are you sure you want to delete this record?'
                ),
                'method' => 'post',
                'pjax'=>'0'
            ],
        ],
```
The form wrap by DetailView widget prevent me to perform Delete action when pressing Delete button.
Could you help me check this kind of issue?
(When place the delete button outside of the form, it perform the delete function as usual)

Best Regards,
Viet.

**Comment by kartik-v** [comment]
The delete button is just a normal HTML hyperlink and should not be dependent on the form wrap. 

Check if you have a pjax request firing as well on click of the button which could be causing logical problems.

**Comment by kartik-v** [comment]
Just an update to my statement.

I see that all buttons are generated as Html buttons... it could be possible that they are being rendered as buttons without a type - will need to check.

If you do not have a button type defined HTML defaults it to a form submit button. It must have a button type set to `button` implicitly.

**Comment by kartik-v** [comment]
EDIT...

I see that delete button is rendered as a hyperlink - so you should not have the issue. You need to debug if its a pjax request or something else firing causing this.

**Comment by lhviet** [comment]
Hi,

Thank you for quick replying.
I checked many times but cannot make it works.
When using Inspect Element function (browser), I just drag the generated <a href="delete....> outside of the form, then it works as usual.

Thank you.

**Comment by kartik-v** [comment]
Ok I just see the problem is with default Yii's routine which uses the `data-method = POST` to generate a new form which is causing a nested form issue.

Options -- 

- not to use data-method = POST and use your own ajax request
- see if anything else can be done to the extension to enhance

**Comment by lhviet** [comment]
Thanks,
Actually, I solved it by using an outside form link (button) separately.
I wonder why save button works (it also using POST method) but the delete button does not?
Are they different somehow?

Best Regards.

**Comment by lhviet** [comment]
UPDATE...

Save is a submit form button. I see... Thank you.

**Comment by kartik-v** [comment]
Yes. That's the reason - the submit button in the SAVE button has to be inside the form for submit to trigger and hence all toolbar has to be inside the form.

I would suggest to use the delete configuration without data-method = POST. Will change the default button configuration - then it will work.

**Comment by kartik-v** [comment]
Yes. That's the reason - the submit via the SAVE button has to be inside the form for submit to trigger and hence all toolbar has to be inside the form.

I would suggest to use the delete configuration without data-method = POST. Will change the default button configuration - then it will work.

On your question any button will work -- within the form tag...including hyperlinks. But using `data-method=POST` is a special Yii option which autogenerates another form and this causes a nested form.

**Comment by kartik-v** [comment]
Refer new enhancements #47, #48, #49.
