### ISSUE TITLE
Multiple detail views on the same page prevent edit/view... buttons to operate

### ISSUE THREAD

**Issue by pgodiani** [kartik-v/yii2-detail-view#54]
Hi,
I'm trying to use the detailview in conjunction with grid view expand column.
The view is pulled from server using Ajax and expands in the grid view.
All works great but there still an issue with the view buttons that do not operate well.
I generated individual ids for all fields and also for view container and view form
but I'm still unable to switch to edit mode.
I suspect that `jQuery("#...").kvDetailView(...);` does not address the appropriate container:
buttons are outside detail view container.
Having the form and view container share the same id seems to improve behavior but not completely

**Comment by kartik-v** [comment]
Hoping you have the latest release of DetailView v1.7.1 -- The DetailView plugin in the newer release is initialized on the `container['id']` - in case you are manually initializing this.

**Comment by pgodiani** [comment]
I'm generating different `container['id']` for each view as you suggest.
Even in 1.7.1, the view is generated as below:
    `<form id="myformid"  ...
         <button> ...
         <div id='mycontainerid* ...from container['id']...*' >
         *the view lies there*
         </div>
    </form>`
but at the end, there's `jQuery("#mycontainerid").kvDetailView... ` which searches 
for buttons in the div when the buttons are outside it.
When I use the same id for both **form** and **container**, the buttons seems to 
work correctly.

**Comment by kartik-v** [comment]
Its incorrect.. you may want to check if you have updated code.. .and cross check this with the demo..

The `form` envelops the `container` and everything else lies inside the container.
