### ISSUE TITLE
INPUT_FILEINPUT detailview not working properly

### ISSUE THREAD

**Issue by fwroman** [kartik-v/yii2-detail-view#55]
Hi again Kartik, I need to update data using detailview and kartik fileinput inside it, so the inputFile seems to send data via post but when I apply UploadedFile::getInstance this function returns null, please could you make a tutorial of how to use detailview with INPUT_FILEINPUT for update data of a model

I hope you can help me, thanks anyway

**Comment by kartik-v** [comment]
This is related to file input plugin and not detail view.

Refer webtips for [basic upload](http://webtips.krajee.com/upload-file-yii-2-using-fileinput-widget/) and [advanced upload](http://webtips.krajee.com/advanced-upload-using-yii2-fileinput-widget/) here.

You can also use [ajax uploads by checking all articles here](http://webtips.krajee.com/tag/fileinput/).

Note that your active form option must have the `'enctype'=>'multipart/form-data'' setting for file input blobs to be detected in your PHP code.

**Comment by TomaszKane** [comment]
Hi @kartik-v,
when I set enctype to form like this:
```php
use kartik\detail\DetailView;

echo DetailView::widget([
    'model' => $foo,
    'mode' => $mode,
    'formOptions' => ['options' => ['enctype' => 'multipart/form-data']],
    'attributes' => [
        [
            'attribute' => 'file',
            'type' => DetailView::INPUT_FILEINPUT,
        ],
    ],
]);
```
Rendered form tag don't have enctype attribute.
http://demos.krajee.com/detail-view#option-formOptions
