### ISSUE TITLE
Cannot work inside yii2-grid (Expand Row Column)

### ISSUE THREAD

**Issue by eugenyho** [kartik-v/yii2-detail-view#57]
Trying to use inside yii2-grid (Expand Row Column). As result in View mode, the button "Edit" is not working. Button clik action must pointed to "kv-detail-view.min.js" but its pointed to "yii.js"

**Comment by kartik-v** [comment]
Do not understand the issue and/or cannot reproduce what you need. Not sure what you mean by pointed to **yii.js**? Closing the issue until you get more details that can be reproduced.
