### ISSUE TITLE
Panel headingOptions not taken into account?

### ISSUE THREAD

**Issue by devleaks** [kartik-v/yii2-detail-view#59]
I want to suppress update/delete buttons from heading in DetailView with following attributes:

```php
	'panel'=>[
	        'heading' => '<h3>'.Yii::t('igolf', $model->competition_type).' '.$model->name.'</h3>',
		'headingOptions' => [
			'template' => '{title}',
		],
	],
```

but headingOptions does not seems to be taken into account.
How can I hide buttons?
Thank you.
P.

**Comment by kartik-v** [comment]
You can check with the updated code from dev-master now.
