### ISSUE TITLE
Text not wrapping properly in value column 

### ISSUE THREAD

**Issue by wilswork** [kartik-v/yii2-detail-view#61]
Hi Kartik,

First of all, I want to thank you for your great work! Your Yii2 stuff is fabulous!
Now for the issue:
Long strings in the value (of a attribute/value pair) do not seem to correctly wrap on small screens.
Here are some simple steps to reproduce this:
1. In any view file generated by gii, replaced DetailView with yours
2. Make sure one of the values is long (e.g. >40 characters)
3. Browse to that model's view, and resize the browser to emulate a mobile screen (e.g. Ctrl+Shift+M in Firefox)

Here is the code snippet I used:
```php
<?= DetailView::widget([
		'model' => $modelCompany,
		'attributes' => [
			'id',
			'name',
		],
	]) ?>
````
Other info:
Yii2 2.0.4 Advanced Template stable

I don't really need the edit mode and only use the view mode of DetailView, and the "group" feature was a blessing.

Thanks in advance,
Wilson

**Comment by kartik-v** [comment]
Not sure I can understand or reproduce what you are saying. You can use your own CSS styles to control how you display content.

For example, check the [demo page](http://demos.krajee.com/detail-view-demo) and view the **synopsis** content which is a LONG text.
