### ISSUE TITLE
Not working with an associative array

### ISSUE THREAD

**Issue by joester89** [kartik-v/yii2-detail-view#63]
The detailview of Yii2 itself works with an associative array. Unfortunately this detail view checks if the model has errors in https://github.com/kartik-v/yii2-detail-view/blob/master/DetailView.php#L632. This causes problems.

Maybe even disable all the editing options when an array is provided?

**Comment by kartik-v** [comment]
Not clear with your need. What is the "associative array" here?

**Comment by joester89** [comment]
Sorry, the "associative array" in this case is used instead of a model.

**Comment by kartik-v** [comment]
Not clear with this issue. Update with more details of the code and screenshots.

**Comment by kartik-v** [comment]
Cannot reproduce the issue OR probably do not understand what is the need here. Update with the code and screenshots.
