### ISSUE TITLE
Create section like in documentation

### ISSUE THREAD

**Issue by adiramardiani** [kartik-v/yii2-detail-view#64]
How to create section like in documentation ?
![section](https://cloud.githubusercontent.com/assets/8703419/8325665/8e19b9d6-1a85-11e5-9227-c5c5946e8531.png)

**Comment by kartik-v** [comment]
Its mentioned in the demo.

Click **Detail View Setup** button for the source code [on the demo page](http://demos.krajee.com/detail-view-demo).
