### ISSUE TITLE
Composer update issue

### ISSUE THREAD

**Issue by devleaks** [kartik-v/yii2-detail-view#71]
`
Problem 1
    - kartik-v/yii2-detail-view dev-master requires kartik-v/yii2-helpers ~1.3 -> no matching package found.
    - kartik-v/yii2-detail-view dev-master requires kartik-v/yii2-helpers ~1.3 -> no matching package found.
    - Installation request for kartik-v/yii2-detail-view dev-master -> satisfiable by kartik-v/yii2-detail-view[dev-master].
`
Any updated package that could cause this?
Thanks.
P.

**Comment by kartik-v** [comment]
You need to check each extension's dependencies from the extension's composer.json (in this case `yii2-detail-view` has dependencies to packages like `yii2-helpers`).

Then recheck your application's composer.json and ensure you have right packages and dependencies. For this use case of yours,  remove `yii2-helpers` from the composer.json, if you want the `dev-master` release of `yii2-detail-view` 

ELSE

If you need specific `yii2-helpers` release and `yii2-detail-view` release put a strict version.
