### ISSUE TITLE
Delete Button with Bootstrap Modal Confirm

### ISSUE THREAD

**Issue by zmoddynamics** [kartik-v/yii2-detail-view#88]
Hi, Thanks for writing this great extension. I am hoping you can help me figure out how to change the default 'confirm' dialog box to one that uses a bootstrap modal confirm?

For example, I also use your gridview  extension and you allow for some callbacks to set a custom button:

'buttons' => [

            //view button
            'delete' => function ($url, $model) {
                return
                    "<button data-toggle=\"modal\" data-target=\"#confirm-delete\" data-action=\"{$url}\" type=\"button\" class=\"btn btn-xs btn-danger\">
                        <span class=\"glyphicon glyphicon-trash\"></span>
                    </button>";

            },
        ],

In this way, I can override your button with my own modal confirm. Is there anyway to do something similar with the delete button of DetailView ?

**Comment by kartik-v** [comment]
Will be implemented via [Krajee Dialog Extension](http://demos.krajee.com/dialog) and a `krajeeDialogSettings` property will be made available to configure the widget.

**Comment by cytoplyu** [comment]
Hi Kartik 

I need to change the label of the buttons inside of the delete cofirmation modal in gridview, can you help me? 

Thanks in advance
