### ISSUE TITLE
hidden input

### ISSUE THREAD

**Issue by williamyiu** [kartik-v/yii2-detail-view#9]
How do I add a hidden input?

**Comment by SSiwek** [comment]
Hi,
it seems that this approach does not work. The hiddenInput fields arent send back.

View:
`
									'attribute' => 'pn_fa_id',
									'value' => ($model->isNewRecord )?'': $model->kommittent->pn_verlag . "\n" 
									. Html::hiddenInput( 'pn_gruppe_fa' ,'')
									. Html::hiddenInput( 'pn_gruppe_huvlg', '' )
									,
									'items' => $verlag_ar,`


The hiddenInputs arent correctly rendered. The "<" and ">" for the input tag become &lt\; and &gt\;  So they arent reocgnized by the browser.
![image](https://cloud.githubusercontent.com/assets/1586351/24752850/02a567cc-1ad0-11e7-8737-82c69e0e5f7b.png)

**Comment by kartik-v** [comment]
Yes its obvious... that's because you have missed the most important part `format => 'raw'`
