### ISSUE TITLE
'columns' attribute triggers error in the base class

### ISSUE THREAD

**Issue by synatree** [kartik-v/yii2-detail-view#90]
![image](https://cloud.githubusercontent.com/assets/7294077/10203617/1e86c012-6785-11e5-82fe-fc3c527b266f.png)

**Comment by davibennun** [comment]
+1

**Comment by davibennun** [comment]
Did you solve this error?

**Comment by dasscheman** [comment]
I'm having the same problem. Any solution?

**Comment by felipe-carrasco** [comment]
Me too, today I tried to use the columns format and that error popped. I deleted the widget folder and reinstalled v1.7.5 and the problem remains.
I tried something as simple as this:
`
<?= DetailView::widget([
    'model' => $model,
    'attributes' => [
    'columns' => [
        [
            'attribute' => 'id_insumo'
        ],
        [
            'attribute' => 'descripcion'
        ],
    ],
        //'id_insumo',
        //'descripcion',
        //'ultimo_precio',
    ],
]) ?>
`

**Comment by kartik-v** [comment]
Cross check your configuration of `columns` with [the demo page](http://demos.krajee.com/detail-view-demo) ... click the Detail View Setup button on the top of the page to see the configuration code.
