### ISSUE TITLE
It is not possible to set label width without overwriting hAlign, vAlign

### ISSUE THREAD

**Issue by nagyt234** [kartik-v/yii2-detail-view#91]
The label width on the field level can be set only in the form of
```
'labelColOptions' => ['style' => "width:10%"],
```
This settings however overwrites the widget level settins of hAlign and vAlign, because they are set also in ```'labelColOptions' => ['style'...```.

The solution could be, that the a ```labelWidth``` option would be introduced on the field level, to avoid to overwrite the entire ```labelColOptions```. Or another, probably general solution to introduce ```labelStyle``` on the field lavel, which could be added to the styles in  ```labelColOptions```.

**Comment by kartik-v** [comment]
Not sure if you have the right release. The `hAlign` and `vAlign` will always be appended to the style in `labelColOptions`.

**Comment by nagyt234** [comment]
I've just updated to the latest version:
```
"url": "https://api.github.com/repos/kartik-v/yii2-detail-view/zipball/346c067db89564ca906f28dc757b3133235e0361"
```
Nothing changed. See my code fragments.
```
$labelAlign = "text-align: right; vertical-align: middle;";
...
    <?php
        $attributes_config = [
            [
                'columns' => [
                    [
                        'attribute' => 'name',
                        'labelColOptions' => ['style' => "$labelAlign width:20%"],
                        'valueColOptions' => ['style' => 'width:35%'],
                    ],
...
    <?= DetailView::widget([
        'mode' => DetailView::MODE_VIEW,
        'model' => $model,
        'condensed' => true, 
        'striped' => false,
        'attributes' => $attributes_config,
        'hAlign' => DetailView::ALIGN_RIGHT,
        'vAlign' => DetailView::ALIGN_MIDDLE,
    ]) ?>               
```
If I totally remove the line ```'labelColOptions' => ['style' => "$labelAlign width:20%"],```, then the label is right aligned correctly based on the widget level setting. If I remove only ```$labelAlign``` from that line than the label is left aligned, i.e. the grid level setting is lost.

**Comment by ajmedway** [comment]
I also have this issue, seems a manual style is needed on 'labelColOptions'
