### ISSUE TITLE
Access ActiveForm instance in custom widgets (DetailView::INPUT_WIDGET)

### ISSUE THREAD

**Issue by vadim-bulochnik** [kartik-v/yii2-detail-view#94]
Hello,

When using custom widget in edit mode it's sometimes needed to access in this widget ActiveForm instance ($_form) that is created in DetailView::init().
The reason is the following: in custom widgets I generate several ActiveField inputs that should be created by ActiveForm instance that used in DetailView edit mode. It's needed to have all js-events binded correctly to the fields (e.g. client validation, ajax validation etc.).

I think it can be achieved by adding form instance to $widgetOptions array in DetailView::renderFormAttribute() method. Something like this:
```php
if (isset($widgetOptions['addFormInstance'])) {
    $widgetOptions['_form'] = $this->_form;
}
```
Do you think this makes sense?

Best regards,
Vadim

**Comment by kartik-v** [comment]
You do not need to do that. The widget automatically will generate an ActiveField using the widget settings. You must set the `widgetOptions` as described in documentation for your custom widget and it will automatically render it as an active form field. You may want to go through [the docs once again for DetailView widget](http://demos.krajee.com/detail-view).

**Comment by vadim-bulochnik** [comment]
Actually I need this, because sometimes I need to create complex widgets that can consists of several input fields. And it's important to use there ActiveForm instance ($_form) that is created in DetailView::init().
Please look at this example: https://monosnap.com/file/v0xUg646JIKgW2zEXXVkwYgrEhwisy

So, just need a way to have possibility to use in custom widgets - ActiveForm instance that is used by DetailView.

Thanks,
Vadim

**Comment by kartik-v** [comment]
Refer #116.
