### ISSUE TITLE
Invalid Configuration – yii\base\InvalidConfigException

### ISSUE THREAD

**Issue by madan3** [kartik-v/yii2-detail-view#96]
hello Kartik

I have problem like this while using ExpandRowColumn..
The class '\kartik\mpdf\Pdf' was not found and is required for PDF export functionality. To include PDF export, follow the install steps below. If you do not need PDF export functionality, do not include 'PDF' as a format in the 'export' property. You can otherwise set 'export' to 'false' to disable all export functionality.

Please ensure you have installed the 'yii2-mpdf' extension. To install, you can run this console command from your application root:

php composer.phar require kartik-v/yii2-mpdf: "@dev"

i update my composer as well but still face same problem.

**Comment by kartik-v** [comment]
Wrong repo... this is a kartik-v/yii2-grid query and you must post there. Anyway as clearly mentioned in the exception message, you need to check your composer setup and package installation to ensure mPDF is installed as
