### ISSUE TITLE
Broken Update/Delete functionality when rendered inside Modal

### ISSUE THREAD

**Issue by IGaMbLeRI** [kartik-v/yii2-detail-view#99]
#### Setup:

View file contains an empty `yii\bootstrap\Modal` : 
`<?php
    Modal::begin([
        'headerOptions' => ['class' => 'modalHeader'],
        'id' => 'schedule-modal',
        'size' => 'modal-lg',
    ]);

```
Modal::end();
```

?>`

which stays hidden until content is dynamically loaded via:

`$(modalBodySelector).load('view-details', {Id:RecordId}, function(){
                    /*some irrelevant stuff here*/
                });`

Now, route 'view-details' leads us to this action : 
`public function actionViewDetails() {
        $post = Yii::$app->request->post();
        if (Yii::$app->request->isAjax) {
            $record = Records::find()->where(['Id' => $post['Id']])->one();
            return $this->renderAjax('modal', [
                'model' => $record
            ]);
        } 
    }`

which renders a simple `modal.php` View file : 
`echo DetailView::widget($DetailViewSettings);`.

Now, the widget renders just fine inside the Modal window, as long as you set unique `id=""` for each container in the widget:
`'formOptions' => ['id' => 'record-details-form'],
    'options' => ['id' => 'record-details-table'],
    'container' => ['id' => 'record-details-widget'],`
Not sure which one did the trick exactly, but was stuck for a couple of hours struggling to understand why clicking on Update stopped triggering the Edit View of the widget. Anyhow..

Although, everything seems to render fine, in this scenario I have some problems:
1. Save Changes button has a generated route `view-details` which essentially triggers `function actionViewDetails () {...}` described above. That poses a certain other problem: _the call to the action is not an AJAX call_ , which forces the page to reload, instead I would be expecting to return a success object from the action to the widget indicating how the Update operation went.
2. Delete button has a separate configurable path, but in this configuration I am unable to actually return the success object back to the widget for display. This is my action for Deleting via Ajax:
`public function actionAjaxDeleteBooking()
    {
        if (Yii::$app->request->isAjax) {
            $id = Yii::$app->request->post('id');
            if ($this->findModel($id)->delete()) {
                return $this->redirect(['index']);
            }
        }
    }`
Returning a JSON doesn't work for some reason - Internal Server Error, when I try to 
'return Json::encode([
'success' => true,
                    'messages' => [
                        'kv-detail-info' => 'The book # ' . $id . ' was successfully deleted. <a href="' . 
                            Url::to(['/site/view']) . '" class="btn btn-sm btn-info">' .
                            '<i class="glyphicon glyphicon-hand-right"></i>  Click here</a> to proceed.'
                    ]]);'
instead of `redirect` (as was gathered from http://webtips.krajee.com/viewing-updating-model-data-yii2-detail-view/ ).

Am I doing something wrong, or is this indeed a bug?

P.S. absolutely loving this extension :)

**Comment by lvbaocheng** [comment]
I have the same question. @IGaMbLeRI Have you solved it？How to save the view asynchronously in the modal？Can you help me? @kartik-v Thank you

**Comment by lvbaocheng** [comment]
The document description is only delete, and there is no Ajax submission for the Sava operation. How do I customize the buttons in view?

**Comment by kartik-v** [comment]
Please understand that this is part of your client code/javascript programming.

You need to write your code appropriately for dynamic content rendered in modal. The DetailView widget will initialize its plugins and javascript code on `document.ready` - but for dynamic content that you are custom rendering via your own javascript - the JS plugin code for DetailView may not be initialized correctly depending on how you are rendering the HTML markup dynamically. 

In many such cases, using Yii's `renderAjax` method to render content in modals via ajax may help. 

Sorry it is difficult to detail out what is to be initialized when - and no this is not any issue or bug with this extension, but the way you need to write your app code.

**Comment by lvbaocheng** [comment]
Thank you!I try to unbind some of the JS events in detail view, and then add JS+PJAX independently to implement
